name: build and test

on:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
    - 'FMMultifieldMapper.sln'
    - 'global.json'
    - '.github/workflows/tests.yml'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - 'FMMultifieldMapper.sln'
    - 'global.json'
    - '.github/workflows/tests.yml'

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build-and-test:
    timeout-minutes: 30

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore FMMultifieldMapper.sln

    - name: Build
      run: dotnet build FMMultifieldMapper.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test FMMultifieldMapper.sln --configuration Release --no-restore --no-build --verbosity normal
