name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    timeout-minutes: 30

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies for FMMultifieldMapperTests
      run: dotnet restore ./src/FMMultifieldMapperTests/FMMultifieldMapperTests.csproj

    - name: Build FMMultifieldMapperTests
      run: dotnet build --configuration Release --no-restore ./src/FMMultifieldMapperTests/FMMultifieldMapperTests.csproj
    
    - name: Test FMMultifieldMapperTests
      run: dotnet test --no-restore --verbosity normal ./src/FMMultifieldMapperTests/FMMultifieldMapperTests.csproj

    - name: Install dependencies for FmSyncTests
      run: dotnet restore ./src/FmSyncTests/FmSyncTests.csproj

    - name: Build FmSyncTests
      run: dotnet build --configuration Release --no-restore ./src/FmSyncTests/FmSyncTests.csproj
    
    - name: Test FmSyncTests
      run: dotnet test --no-restore --verbosity normal ./src/FmSyncTests/FmSyncTests.csproj